desafio/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'welcome#index'
  
  scope 'writers' do
    get '/', to: 'writers#index', as: :writers
    post '/', to: 'writers#create'
    get '/new', to: 'writers#new', as: :new_writer
    get '/:id/edit', to: 'writers#edit', as: :edit_writer
    get '/:id', to: 'writers#show', as: :writer
    patch '/:id', to: 'writers#update'
    delete '/:id', to: 'writers#destroy'
  end

  scope 'books' do
    get '/', to: 'books#index', as: :books
    post '/', to: 'books#create'
    get '/new', to: 'books#new', as: :new_book
    get '/:id/edit', to: 'books#edit', as: :edit_book
    get '/:id', to: 'books#show', as: :book
    patch '/:id', to: 'books#update'
    delete '/:id', to: 'books#destroy'
  end
end

desafio/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

desafio/app/models/book.rb
class Book < ApplicationRecord
  validates :name, presence: true
  validates :writer_id, presence: true
  belongs_to :writer
end

desafio/app/models/writer.rb
class Writer < ApplicationRecord
  validates :name, presence: true
  has_many :books
end

desafio/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

desafio/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end 

  def new
    @book = Book.new
    @writers = Writer.all
  end

  def create
    @book = Book.new(book_params)

    begin
      @book.save!
      flash[:notice] = 'sucesso'
    rescue => exception
      flash[:notice] = 'falha'  
    ensure
      redirect_to books_path()
    end
  end

  def edit
    @book = Book.find(params[:id])
    @writers = Writer.all
  end

  def update
    @book = Book.find(params[:id])
    begin
      @book.update!(book_params)
      flash[:notice] = 'sucesso'        
    rescue => exception
      flash[:notice] = 'falha'        
    ensure
      redirect_to books_path()      
    end
  end

  def destroy
    @book = Book.find(params[:id])

    begin
      @book.destroy!
      flash[:notice] = 'livro deletado com sucesso'
    rescue => exception
      flash[:notice] = 'falha'
    ensure
      redirect_to books_path()
    end
  end


  private
    def book_params
      params.require(:book).permit(:name, :year, :writer_id)
    end
end

desafio/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

desafio/app/controllers/writers_controller.rb
class WritersController < ApplicationController

  def index
    @writers = Writer.all
  end

  def show
    @writer = Writer.find(params[:id])
  end 

  def new
    @writer = Writer.new
  end

  def create
    @writer = Writer.new(writer_params)

    begin
      @writer.save!
      flash[:notice] = 'sucesso'
    rescue => exception
      flash[:notice] = 'falha'  
    ensure
      redirect_to writers_path()
    end
  end

  def edit
    @writer = Writer.find(params[:id])
  end

  def update
    @writer = Writer.find(params[:id])
    begin
      @writer.update!(writer_params)
      flash[:notice] = 'sucesso'        
    rescue => exception
      flash[:notice] = 'falha'        
    ensure
      redirect_to writers_path()      
    end
  end

  def destroy
    @writer = Writer.find(params[:id])

    begin
      @writer.destroy!
      flash[:notice] = 'autor deletado com sucesso'
    rescue => exception
      flash[:notice] = 'falha'
    ensure
      redirect_to writers_path()
    end
  end


  private
    def writer_params
      params.require(:writer).permit(:name, :birth_year, :country)
    end
end

desafio/app/helpers/application_helper.rb
module ApplicationHelper
end

desafio/app/helpers/books_helper.rb
module BooksHelper
end

desafio/app/helpers/welcome_helper.rb
module WelcomeHelper
end

desafio/app/helpers/writers_helper.rb
module WritersHelper
end

desafio/app/views/books/edit.html.erb
<h1 class='title'>Editar</h1>

<%= form_for @book do |f| %>
  <span>Nome</span>
  <%= f.text_field :name%>
  <span>Ano</span>
  <%= f.number_field :year%>
  <span>Escritor</span>
  <%= f.select :writer_id, @writers.collect {|writer| [writer.name, writer.id]}%>
  <%= f.submit %>
<% end %>

<%= link_to  "Voltar", books_path() %>

desafio/app/views/books/index.html.erb
<h1 class='title' >Todos os livros</h1>

<% @books.each do |book| %>
  <div class='cell'>
    <span><%= book.name %></span>
    <%= link_to  "Mais", book_path(book.id) %>
    <%= link_to  "Editar", edit_book_path(book.id) %>
    <%= button_to  "Deletar", book_path(book.id), method: :delete %>
  </div>
<% end %>

<%= link_to  "Criar", new_book_path() %>
<%= link_to  "Voltar", root_path() %>

<p><%= flash[:notice] %></p>

desafio/app/views/books/new.html.erb
<h1 class='title'>Novo livro: </h1>

<%= form_for @book do |f| %>
  <span>Nome</span>
  <%= f.text_field :name%>
  <span>Ano</span>
  <%= f.number_field :year%>
  <span>Escritor</span>
  <%= f.select :writer_id, @writers.collect {|writer| [writer.name, writer.id]}%>
  <%= f.submit %>
<% end %>

<%= link_to  "Voltar", books_path() %>

desafio/app/views/books/show.html.erb
<h1 class='title'>Show</h1>

<strong>Nome</strong>
<%= @book.name %>
<strong>Ano</strong>
<%= @book.year %>
<strong>Escritor</strong>
<%= @book.writer.name %>

<%= link_to  "Voltar", books_path() %>

desafio/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desafio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

desafio/app/views/welcome/index.html.erb
<h1 class='title'>Desafio semana 3</h1>

<section class='links'>
  <%= link_to books_path(), :class => 'link' do %>
    <div>
      <span>Livros</span>
    </div>
  <% end %>

  <%= link_to writers_path(), :class => 'link' do %>
    <div>
      <span>Escritores</span>
    </div>
  <% end %>
<section>

desafio/app/views/writers/edit.html.erb
<h1 class='title'>Editar</h1>
<%= form_for @writer do |f| %>
  <span>Nome</span>
  <%= f.text_field :name%>
  <span>Ano de nascimento</span>
  <%= f.number_field :birth_year%>
  <span>País</span>
  <%= f.text_field :country%>

  <%= f.submit %>
<% end %>

<%= link_to  "Voltar", writers_path() %>

desafio/app/views/writers/index.html.erb
<h1 class='title'>Todos os escritores</h1>

<% @writers.each do |writer| %>
  <div class='cell'>
    <span><%= writer.name %></span>
    <%= link_to  "Mais", writer_path(writer.id) %>
    <%= link_to  "Editar", edit_writer_path(writer.id) %>
    <%= button_to  "Deletar", writer_path(writer.id), method: :delete %>
  </div>
<% end %>

<%= link_to  "Criar", new_writer_path() %>
<%= link_to  "Voltar", root_path() %>

<p><%= flash[:notice] %></p>

desafio/app/views/writers/new.html.erb
<h1 class='title'>Novo escritor: </h1>

<%= form_for @writer do |f| %>

  <span>Nome</span>
  <%= f.text_field :name%>
  <span>Ano de nascimento</span>
  <%= f.number_field :birth_year%>
  <span>País</span>
  <%= f.text_field :country%>

  <%= f.submit %>
<% end %>

<%= link_to  "Voltar", writers_path() %>

desafio/app/views/writers/show.html.erb
<h1 class='title'>Show</h1>

<strong>Nome</strong>
<%= @writer.name %>
<strong>Nascimento</strong>
<%= @writer.birth_year %>
<strong>País</strong>
<%= @writer.country %>

<%= link_to  "Voltar", writers_path() %>